deploy-defaults: &deployDefaults
  working_directory: ~/ml_application_template
  docker:
      - image: circleci/python:3.6.1
  steps:
    - checkout
    - attach_workspace:
        at: ~/ml_application_template
    - run: cd deploy && terragrunt apply -auto-approve
version: 2
jobs:
  build_and_test:
    working_directory: ~/ml_application_template
    docker:
      - image: circleci/python:3.6.1
    environment:
      ENV: dev
 
    steps:
      - checkout
      - attach_workspace:
          at: ~/ml_application_template
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - requirements-{{ checksum "frontend_api/src/requirements.txt" }}
      - run: 
        name: Install dependencies and run tests
        command: |
            cd frontend_api/src && sudo pip install -r requirements.txt -t .
            python -m unittest discover
      - save_cache:
          key: requirements-{{ checksum "requirements.txt" }}
          paths:
            - frontend_api/src
      - persist_to_workspace:
          root: .
          paths:
            - frontend_api/src

  deploy_dev:
    <<: *deployDefaults
    environment:
      TF_VAR_environment: dev
      TF_VAR_region: ap-southeast-2
      TF_VAR_account: nonprod
      

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test:
          context: personal_account
      - deploy_dev:
          requires:
            - build_and_test
          context: personal_account
          filters:
            branches:
              only: master